require 'rubygems'
require 'hackboxen'
require 'nokogiri'
require 'open-uri'

task :move_template do
  sh "cp config/icss.json #{path_to(:rawd_dir)}" unless File.exist?(File.join(path_to(:rawd_dir), "icss.json"))
end

task :get_data do
  #The catalog is a single page of datasets in alphabetical order.
  #It appears that the catalog page has most of the data we'll need, but that
  #individual dataset pages have the description and dataset size.
  begin
    puts "Pulling the catalog page."
    listing = Nokogiri::HTML(open(WorkingConfig[:catalog_url]))
    listing.xpath("//h3").each {|d| get_dataset_page d.children.attribute('href').to_s}
  rescue
    puts("Error connecting, processing local files.")
  end
end

def get_dataset_page url
  path = File.join(path_to(:ripd_dir), File.basename(url))
  return if File.exist?(path)
  sh "wget -O #{path} #{url}" unless File.size?(path)
  #File.new(path,'w').write(open(url).read)
end

task :default => ['hb:create_working_config', :move_template, :get_data, 'hb:init']
